-- RESTORE POINT: 2026-02-13T22:05:35-07:00
-- Updated: 2026-02-13T23:13:13-07:00
-- Updated: 2026-02-13T23:49:04-07:00
-- This file serves as a restore point before adding new plugins.
-- To restore, remove the newly added plugin files and this file.
--
-- Plugins added in this session:
-- 1. lua/plugins/bigfile.lua - Large file performance optimization
-- 2. lua/plugins/cloak.lua - Hide sensitive data in env files
-- 3. lua/plugins/illuminate.lua - Highlight word under cursor
-- 4. lua/plugins/inlayhints.lua - LSP inlay hints
-- 5. lua/plugins/legendary.lua - Keybinding management with duplicate.nvim
-- 6. lua/plugins/lspsaga.lua - Enhanced LSP UI
-- 7. lua/plugins/rustaceanvim.lua - Enhanced Rust support
-- 8. lua/plugins/tiny-devicons-auto-colors.lua - Auto-colored devicons
--
-- Fix applied 2026-02-13T22:05:35-07:00:
--   - lua/plugins/treesitter_extended.lua: Removed config function that was
--     trying to require 'nvim-treesitter.configs' which no longer exists in
--     nvim-treesitter 1.0+. The file now only declares the plugin as a
--     dependency without a config function.
--
-- Fix applied 2026-02-13T23:13:13-07:00:
--   - init.lua (nvim-ufo config): Fixed E1511 error "Wrong number of characters
--     for field foldopen". Changed vim.o.fillchars string assignment to
--     vim.opt.fillchars table assignment to avoid parsing issues and ensure
--     no invalid fold-related fields (foldopen, foldsep, foldclose) are set.
--     These fields require single-byte ASCII chars only.
--
-- Fix applied 2026-02-13T23:49:04-07:00:
--   - init.lua: Enhanced ft_to_lang shim to use rawset() for robustness.
--     The previous shim could potentially be overwritten by lazy-loaded modules.
--     Now uses rawset() to bypass metatables and stores in _G for persistence.
--     Error was: "attempt to call field 'ft_to_lang' (a nil value)" in Telescope.
--
-- To restore to previous state:
-- 1. Delete the above plugin files
-- 2. Delete this restore point file
-- 3. Run :Lazy sync
--
-- To restore fillchars fix only:
--   In init.lua nvim-ufo config, change:
--     vim.opt.fillchars = { eob = " ", fold = " " }
--   Back to:
--     vim.o.fillchars = "eob: ,fold: "
--
-- To restore ft_to_lang fix only:
--   In init.lua, revert the ft_to_lang shim block to use simple assignment
--   instead of rawset and _G storage.

return {}
